plugins:
  - prettier
env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0
  prettier/prettier: error
